server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
  redis:
    enabled: false

servicios:
  sri-url: http://localhost:8081/api/sri/contribuyente
  vehiculo-url: http://localhost:8082/api/vehiculo
  ant-url: http://localhost:8083/api/ant/puntos

cloud:
  gateway:
    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins:
            - "http://localhost:5175"
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowedHeaders:
            - "*"
          allowCredentials: true